# GAE deployment configuration
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

beta_settings:
  cloud_sql_instances: tinhtt-007:asia-east1:postgres-001

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
  
runtime_config:
  operating_system: "ubuntu22"